### ISSUE TITLE
missing FormattedSDDLText

### ISSUE THREAD

**Issue by oldoldman** [mdsteele/rust-msi#11]
I'm trying to open the blank template Schema.msi from MSI SDK, Package::open panic with ```Invalid category: FormattedSDDLText```error. From [this doc](https://docs.microsoft.com/en-us/windows/win32/msi/column-data-types) it seems FormattedSDDLText is an officially supported data type. Maybe it is missed from rust-msi ? I have compared the Category enum with the official doc, found the following differences
```
rust-msi            official doc
---------------------------------------
missed              FormattedSDDLText
missed              Time/Date
KeyFormatted        missed
Url                 missed
---------------------------------------
```

**Comment by mdsteele** [comment]
Should be easy enough to add `FormattedSDDLText` and `Time/Date`.  Can you link to the `Schema.msi` file you're using (or just post the file here) so I can test it out?

**Comment by oldoldman** [comment]
this is the file I'm trying to open with.
[Schema.zip](https://github.com/mdsteele/rust-msi/files/7799065/Schema.zip) , or you can check this [link](https://github.com/ojdkbuild/tools_toolchain_sdk71/blob/master/Bin/msitools/Schemas/MSI/Schema.Msi) for more. Thank you for maintaining this project!

**Comment by mdsteele** [comment]
Thanks!  With the above commit I just pushed (bba603e), reading that `Schema.msi` file seems to work fine now.
