### ISSUE TITLE
The encoding crate is unmaintained

### ISSUE THREAD

**Issue by messense** [mdsteele/rust-msi#14]
https://github.com/rustsec/advisory-db/issues/1605

Is it possible to migrate to [`encoding_rs`](https://docs.rs/encoding_rs)?

**Comment by ikrivosheev** [comment]
@messense the biggest problem to migrate to encoding_rs is it doesn't support `ASCII` encoding.

**Comment by mdsteele** [comment]
Seems like it shouldn't be too hard to emulate the `ASCII` encoding behavior of the old `encoding` crate by hand (which I believe just replaces any non-ASCII characters with `'?'` when encoding; see [this `rust-msi` unit test](https://github.com/mdsteele/rust-msi/blob/c06836d15c0b289a670e97122e8df884a5e26d8d/src/internal/codepage.rs#L311)).

If anyone wants to take a shot at this, a PR would be very welcome.

**Comment by messense** [comment]
I took a naive shot in https://github.com/mdsteele/rust-msi/pull/15, please take a look, thanks!
