### ISSUE TITLE
Update cfb dependency

### ISSUE THREAD

**Issue by russellbanks** [mdsteele/rust-msi#17]
When I open a Temurin MSI, I get `Malformed MiniFAT (MiniFAT has 606 entries, but root stream has only 605 mini sectors)`:

```rust
msi::open(r"path\to\OpenJDK21U-jre_x64_windows_hotspot_21_35.msi").unwrap();
```

I've tried with different versions of Temurin but get the same error with different numbers.

There seems to be a [potential fix](https://github.com/mdsteele/rust-cfb/pull/35) for this in cfb 0.8.0 but this library uses cfb 0.7.3.

To reproduce, here's the link to the MSI:
- [Download page](https://adoptium.net/temurin/releases/?os=windows&arch=x64&package=jre)
- [Direct download link](https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21%2B35/OpenJDK21U-jre_x64_windows_hotspot_21_35.msi)

**Comment by mdsteele** [comment]
Thanks!  I was able to reproduce the error, and I've updated the `cfb` dependency to the latest version, which seems to fix it.  I've just published a [new version](https://crates.io/crates/msi/0.7.0) of `msi` with the updated dependency.
