### ISSUE TITLE
Need to skip `\u{5}DocumentSummaryInformation` for streams too

### ISSUE THREAD

**Issue by shamilsan** [mdsteele/rust-msi#28]
Here we skip some streams with special names (`\u{5}DigitalSignature`, `\u{5}MsiDigitalSignatureEx`, `\u{5}SummaryInformation`):

https://github.com/mdsteele/rust-msi/blob/v0.7.0/src/internal/stream.rs#L86-L92

But it looks like we need to skip the `\u{5}DocumentSummaryInformation` stream as well.

Similar issue: https://github.com/mdsteele/rust-msi/issues/6

**Comment by mdsteele** [comment]
Sounds reasonable.  Would you be up for making a PR for this?

**Comment by shamilsan** [comment]
Yes, I'll do it.

**Comment by shamilsan** [comment]
Dear @mdsteele,

Thank you very much for merging my PRs! May I ask you if it is possible to publish a patch version of the library (e.g. `v0.7.1`)? It would be very much appreciated!

**Comment by mdsteele** [comment]
Published as [v0.8.0](https://crates.io/crates/msi/0.8.0).
