### ISSUE TITLE
Panic when using with WASM target

### ISSUE THREAD

**Issue by andyolivares** [mdsteele/rust-msi#31]
When using this library using the WASM target, I get a panic with the following message:

```
panicked at library/std/src/time.rs:617:31:
overflow when subtracting duration from instant
```

Tracking down the problem, seems to be an issue when calculating between **SystemTime to u64** and viceversa.

https://github.com/mdsteele/rust-msi/blob/56efa8913536ed463cf5f0813c3283e732488b81/src/internal/time.rs#L28

For some reason the WASM stdlib has an issue with substracting from UNIX_EPOCH.

Forked the library, and removed SystemTime converstions alltogether (just using u64 inside PropertyValue::FileTime) and the panic in WASM goes away: https://github.com/andyolivares/rust-msi/tree/feature/no_time

I would suggest using another time library to make these calculations (chronos perhaps?) or use u64 everywhere and let the user convert to SystemTime when needed.

**Comment by mdsteele** [comment]
Hmm, you may be right about changing the API to move away from `SystemTime` at some point.  In the meantime, though, I've pushed some changes to be a little more careful with the internal `SystemTime` calculations to avoid the overflow/underflow.  Could you check if that fixes it for you on WASM?

**Comment by andyolivares** [comment]
I can confirm that the library doesn't panic anymore after your changes. As you said in your commit, if it gets an error result, it will be a wrong `SystemTime`.

I still believe that moving away from SystemTime would be a better option. Maybe you can include helper functions to convert to/from `SystemTime` but not make it mandatory.

Thank you so much for the help tho. I think you can close this issue for now :)
