### ISSUE TITLE
Write stream

### ISSUE THREAD

**Issue by otech-nl** [mdsteele/rust-msi#33]
Hello,

Thanks for providing this library.

I am trying to 'reverse' the `extract` operation of the `msiinfo` example: write a binary stream to a package, like so:

```rust
let mut fin = File::open(&args.name).expect("open file");
let mut stream = package.write_stream(&args.name).expect("write stream");
io::copy(&mut fin, &mut stream).expect("insert");
```
where `args.name` is a `String` with a value from the streams list.

This fails on the `write_stream` in the call to [create_stream_with_path](https://github.com/mdsteele/rust-cfb/blob/6594a4732c1b7b51cc076353b4888c3beb864597/src/lib.rs#L833) of the `cfb` crate with "Bad file descriptor".

Any advice would be appreciated.

**Comment by mdsteele** [comment]
Did you open the file in writable mode?  [`File::open`](https://doc.rust-lang.org/std/fs/struct.File.html#method.open) opens in read-only mode.

**Comment by otech-nl** [comment]
Thanks for your response.

I am only reading from the file, so RO should be fine.

But I did _not_ open the _package_ RW, so when I changed `msi::open` to `msi::open_rw`, the error went away.

I should have seen that, thanks. But the error message from `cfb` could be clearer...

**Comment by otech-nl** [comment]
Would it make sense to have `Package::write_stream` fail if the package has been open RO?

I would be willing to prepare a PR and looked if there would be an easy way to check the file permissions of a package, but could not find any, other than adding a `rw: bool` field to the `Package` struct.
